EnvCrime/Components/NavigationViewComponent.cs
using EnvCrime.Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;

namespace EnvCrime.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private readonly EmployeeService employeeService;

        public NavigationViewComponent(EmployeeService empService)
        {
            employeeService = empService;
        }

        public IViewComponentResult Invoke()
        {
            var roleName = employeeService.GetLoggedInEmployeeRoleTitle();
            if (roleName != "Investigator" && roleName != "Coordinator" && roleName != "Manager" && roleName != "Administrator")
            {
                throw new ArgumentException("Invalid role name passed to the Navigation ViewComponent");
            }
            
            ViewBag.ControllerName = roleName;
            ViewBag.StartActionName = "Start" + roleName;
            return View("Navigation");
        }
    }
}

EnvCrime/Views/Shared/_Public.cshtml
<!DOCTYPE html>

<html lang="sv">
<head>
    <meta name="viewport" content="width=device-width" charset="utf-8" />
    <title>Småstads kommun</title>
    <link rel="stylesheet" href="../css/style.css" />
</head>
<body>
    <div id="wrapper">
        <header id="logo">
            <h1>Småstad</h1>
            <p>Kommunen där vi bryr oss om varandra</p>
        </header><!-- End header -->

        <nav>
            <ul>
                @switch(ViewBag.Role)
                {
                    case "Citizen":
                        <li><a asp-controller="Home" asp-action="Index">Hem</a></li>
                        <li><a asp-controller="Citizen" asp-action="Services">Tjänster</a></li>
                        <li><a asp-controller="Citizen" asp-action="Faq">FAQ</a></li>
                        <li><a asp-controller="Citizen" asp-action="Contact">Kontakt</a></li>
                        <li class="right"><a class="login" asp-controller="Home" asp-action="Login">Logga in (endast personal)</a></li>
                    break;
                    case "Manager":
                        <li><a class="reports" asp-controller="Manager" asp-action="StartManager">Start(Ärenden)</a></li>
                        <li class="right"><a class="logout" asp-controller="Home" asp-action="Login">Logga ut</a></li>
                    break;
                    case "Investigator":
                        <li><a class="reports" asp-controller="Investigator" asp-action="StartInvestigator">Start(Ärenden)</a></li>
                        <li class="right"><a class="logout" asp-controller="Home" asp-action="Login">Logga ut</a></li>
                    break;
                    case "Coordinator":
                        <li><a class="reports" asp-controller="Coordinator" asp-action="StartCoordinator">Start(Ärenden)</a></li>
                        <li><a class="reportAdd" asp-controller="Coordinator" asp-action="ReportCrime">Rapportera brott</a></li>
                        <li class="right"><a class="logout" asp-controller="Home" asp-action="Login">Logga ut</a></li>
                    break;
                }
            </ul>
        </nav><!-- End Nav -->

        <div id="content">
            @if (ViewBag.Role == "Citizen")
            {
                <section id="mainColumn">
                    @RenderBody()
                </section><!-- End Left -->

                <aside id="sideColumn">
                    <img src="../images/pic_1.jpg" height="162" alt="Ett barn blåser på en maskros" />
                    <img src="../images/pic_2.jpg" height="162" alt="Åkrar utanför Småstad med hus och kyrkan i bakgrunden" />
                    <img src="../images/pic_3.jpg" height="162" alt="Flygbild över Småstads villaområde" />
                    <img src="../images/pic_4.jpg" height="162" alt="En kvinna vänder ansiktet mot solen och vinden rör om hennes hår" />
                    <img src="../images/pic_5.jpg" height="162" alt="En åker vid första frosten" />
                    <img src="../images/pic_6.jpg" height="162" alt="Händer som håller i jord och en liten planta" />
                    <img src="../images/pic_7.jpg" height="162" alt="Barn liggandes på gräsmatta" />
                    <img src="../images/pic_8.jpg" height="162" alt="Närbild av en fotboll" />
                </aside><!-- End Right -->
            } 
            else
            {
                @RenderBody()
            }

            <footer>
                &copy; Småstads Kommun All rights reserved.
            </footer>
        </div><!-- End Content -->
    </div><!-- End Wrapper -->
</body>
</html>

EnvCrime/Views/Shared/_Staff.cshtml
<!DOCTYPE html>

<html lang="sv">
<head>
    <meta name="viewport" content="width=device-width" charset="utf-8" />
    <title>Småstads kommun</title>
    <link rel="stylesheet" href="../css/style.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    <div id="wrapper">
        <header id="logo">
            <h1>Småstad</h1>
            <p>Kommunen där vi bryr oss om varandra</p>
        </header><!-- End header -->

        <!-- Navigation -->
        @await Component.InvokeAsync("Navigation")

        <div id="content">
            @RenderBody()
            <footer>
                &copy; Småstads Kommun All rights reserved.
            </footer>
        </div><!-- End Content -->
    </div><!-- End Wrapper -->
</body>
</html>