EnvCrime/Controllers/AdministratorController.cs
using EnvCrime.Infrastructure.Services;
using EnvCrime.Infrastructure.Shared.Helpers;
using EnvCrime.Models.dto;
using EnvCrime.Models.poco;
using Microsoft.AspNetCore.Mvc;

namespace EnvCrime.Controllers
{
    public class AdministratorController : Controller
    {
        private readonly AuthenticationHelperService authenticationService;
        private readonly ErrandStatusService errandStatusService;
        private readonly DepartmentService departmentService;
        private readonly EmployeeService employeeService;
        
        public AdministratorController(AuthenticationHelperService authService, ErrandStatusService errStatService, DepartmentService deptService, EmployeeService empService)
        {
            authenticationService = authService;
            errandStatusService = errStatService;
            departmentService = deptService;
            employeeService = empService;
        }

        public ViewResult AdministerStatuses()
        {
            return View(errandStatusService.GetAll());
        }

        public ViewResult EditStatus(String statusId)
        {
            ErrandStatus status = errandStatusService.GetById(statusId);
            if (status == null)
            {
                status = new ErrandStatus() { StatusId = "" };
            }
            ViewBag.NewStatus = string.IsNullOrWhiteSpace(status.StatusId);
            return View("EditStatus", status);
        }

        public IActionResult SaveChanges(ErrandStatus status)
        {
            // ett nyligen-konstruerat objekt inte ligger på db-kontexten från början och kommer inte att sparas även om man kallar .SaveChanges(). Antingen .Add() ska kallas före sparandet eller en existerande version av objektet får hämtas ut från dataabsen och sedan updateras
            var errandStatus = errandStatusService.GetById(status.StatusId);
            if (errandStatus != null)
            {
                errandStatus.StatusName = status.StatusName;
                errandStatusService.Save(errandStatus);
            }
            else
            {
                errandStatusService.Save(status);
            }
            return RedirectToAction("AdministerStatuses");
        }

        public IActionResult DeleteStatus(String statusId)
        {
            errandStatusService.DeleteById(statusId);
            return RedirectToAction("AdministerStatuses");
        }

        public ViewResult AdministerDepartments()
        {
            return View(departmentService.GetAll());
        }

        public ViewResult EditDepartment(String deptId)
        {
            Department department = departmentService.GetById(deptId);
            if (department == null)
            {
                department = new Department() { DepartmentId = "" };
            }
            ViewBag.NewDepartment = string.IsNullOrWhiteSpace(department.DepartmentId);
            return View("EditDepartment", department);
        }

        public IActionResult SaveDepartment(Department department)
        {
            var dept = departmentService.GetById(department.DepartmentId);
            if (dept != null)
            {
                dept.DepartmentName = department.DepartmentName;
                departmentService.Save(dept);
            }
            else
            {
                departmentService.Save(department);
            }
            return RedirectToAction("AdministerDepartments");
        }

        public IActionResult DeleteDepartment(String deptId)
        {
            departmentService.DeleteById(deptId);
            return RedirectToAction("AdministerDepartments");
        }

        public ViewResult AdministerEmployees(EmployeeSearchQuery query)
        {
            var employees = employeeService.Search(query);
            ViewBag.Employees = employees;
            ViewBag.ResultsExist = employees.Any();
            ViewBag.Departments = departmentService.GetAll();
            ViewBag.Roles = authenticationService.GetRoles();
            return View();
        }

        public ViewResult EditEmployee(String employeeId)
        {
            Employee emp = employeeService.GetById(employeeId);
            if (emp == null)
            {
                emp = new Employee() { EmployeeId = "" };
            }
            ViewBag.NewEmployee = string.IsNullOrWhiteSpace(emp.EmployeeId);
            ViewBag.Roles = authenticationService.GetRoles();
            ViewBag.Departments = departmentService.GetAll();
            return View("EditEmployee", emp);
        }

        public async Task<IActionResult> SaveEmployee(Employee employee)
        {
            var emp = employeeService.GetById(employee.EmployeeId);
            if (emp != null)
            {
                emp.EmployeeName = employee.EmployeeName;
                emp.RoleTitle = employee.RoleTitle;
                emp.DepartmentId = employee.DepartmentId;
                employeeService.Save(emp);
            }
            else
            {
                employeeService.Save(employee);
                await employeeService.AddUserIdentity(employee);
            }
            return RedirectToAction("AdministerEmployees");
        }

        public async Task<IActionResult> DeleteEmployee(String employeeId)
        {
            await employeeService.RemoveUserIdentity(employeeService.GetById(employeeId));
            employeeService.DeleteById(employeeId);
            return RedirectToAction("AdministerEmployees");
        }
    }
}

EnvCrime/Views/Administrator/AdministerDepartments.cshtml
@model IEnumerable<Department>

@{
    Layout = "_Staff";
}

<h2>Avdelningar</h2>
<p class="info">Du är inloggad som administratör</p>
<span><a class="button right" asp-controller="Administrator" asp-action="EditDepartment" asp-route-deptId="0">Lägg till</a></span>

@if (Model.Any())
{
    <table>
        <tr>
            <th>Id</th>
            <th>Namn</th>
            <th></th>
        </tr>
        @foreach (var dept in Model)
        {
            <tr>
                <td>@dept.DepartmentId</td>
                <td>@dept.DepartmentName</td>
                <td>
                    <a asp-controller="Administrator" asp-action="EditDepartment" asp-route-deptId="@dept.DepartmentId"><img src="../images/edit.png" height="16" width="16" /></a>
                    <a asp-controller="Administrator" asp-action="DeleteDepartment" asp-route-deptId="@dept.DepartmentId"><img src="../images/delete.png" height="16" width="16" /></a>
                </td>
            </tr>
        }
    </table>
}
@if (!Model.Any())
{
    <p style="text-align:center">
        <i>Inga avdelningar finns</i>
    </p>
}

EnvCrime/Views/Administrator/AdministerEmployees.cshtml
@model EmployeeSearchQuery

@{
    Layout = "_Staff";
}

<h2>Anställda</h2>
<p class="info">Du är inloggad som administratör</p>
<span><a class="button right" asp-controller="Administrator" asp-action="EditEmployee" asp-route-employeeId="0">Lägg till</a></span>

<table id="managerForm">
    <tr>
        <td class="label">Id:</td>
        <td class="label">Namn:</td>
        <td class="label">Välj roll:</td>
        <td class="label">Välj avdelning:</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <form method="post" asp-controller="Administrator" asp-action="AdministerEmployees">
            <td><input asp-for="EmployeeId" /></td>
            <td><input asp-for="EmployeeName" /></td>
            <td>
                <select asp-for="RoleTitle" asp-items="@(new SelectList(ViewBag.Roles, "Name", "Name"))">
                    <option selected value="">Välj alla</option>
                </select>
            </td>
            <td>
                <select asp-for="DepartmentId" asp-items="@(new SelectList(ViewBag.Departments, "DepartmentId", "DepartmentName"))">
                    <option selected value="">Välj alla</option>
                </select>
            </td>
            <td><input class="button" type="submit" value="Sök" /></td>
        </form>
    </tr>
</table>

@if (ViewBag.ResultsExist)
{
    <table>
        <tr>
            <th>Id</th>
            <th>Namn</th>
            <th>Rollnamn</th>
            <th>Avdelning Id</th>
            <th></th>
        </tr>
        @foreach (var employee in ViewBag.Employees)
        {
            <tr>
                <td>@employee.EmployeeId</td>
                <td>@employee.EmployeeName</td>
                <td>@employee.RoleTitle</td>
                <td>@employee.DepartmentName</td>
                <td>
                    <a asp-controller="Administrator" asp-action="EditEmployee" asp-route-employeeId="@employee.EmployeeId"><img src="../images/edit.png" height="16" width="16" /></a>
                    <a asp-controller="Administrator" asp-action="DeleteEmployee" asp-route-employeeId="@employee.EmployeeId"><img src="../images/delete.png" height="16" width="16" /></a>
                </td>
            </tr>
        }

    </table>
}
@if (!ViewBag.ResultsExist)
{
    <p style="text-align:center">
        <i>Inga anställda finns</i>
    </p>
}

EnvCrime/Views/Administrator/AdministerStatuses.cshtml
@model IEnumerable<ErrandStatus>

@{
    Layout = "_Staff";
}

<h2>Statuser</h2>
<p class="info">Du är inloggad som administratör</p>
<span><a class="button right" asp-controller="Administrator" asp-action="EditStatus" asp-route-statusId="0">Lägg till</a></span>

@if (Model.Any())
{
    <table>
        <tr>
            <th>Id</th>
            <th>Namn</th>
            <th></th>
        </tr>
        @foreach (var status in Model)
        {
            <tr>
                <td>@status.StatusId</td>
                <td>@status.StatusName</td>
                <td>
                    <a asp-controller="Administrator" asp-action="EditStatus" asp-route-statusId="@status.StatusId"><img src="../images/edit.png" height="16" width="16" /></a>
                    <a asp-controller="Administrator" asp-action="DeleteStatus" asp-route-statusId="@status.StatusId"><img src="../images/delete.png" height="16" width="16" /></a>
                </td>
            </tr>
        }
    </table>
}
@if (!Model.Any())
{
    <p style="text-align:center">
        <i>Inga statuser finns</i>
    </p>
}

EnvCrime/Views/Administrator/EditDepartment.cshtml
@model Department

@{
    Layout = "_Staff";
}

<h2>Detaljer för avdelning: @(ViewBag.NewDepartment ? "ny avdelning" : Model.DepartmentId)</h2>
<p class="info">Du är inloggad som administratör</p>

<form method="post" asp-controller="Administrator" asp-action="SaveDepartment">
    <p>
        <label asp-for="DepartmentId" class="label">Id:</label><br />
        @if (ViewBag.NewDepartment)
        {
            <input asp-for="DepartmentId" />
        }
        else
        {
            <input asp-for="DepartmentId" readonly value="@Model.DepartmentId" />
        }
        <span asp-validation-for="DepartmentId" style="color: orange"></span>
    </p>
    <p>
        <label asp-for="DepartmentName" class="label">Namn:</label><br />
        <input asp-for="DepartmentName" />
        <span asp-validation-for="DepartmentName" style="color: orange"></span>
    </p>
    <p>
        <input class="button" type="submit" value="Spara" />
    </p>
</form>

EnvCrime/Views/Administrator/EditEmployee.cshtml
@model Employee

@{
    Layout = "_Staff";
}

<h2>Detaljer för anställd: @(ViewBag.NewEmployee ? "ny anställd" : Model.EmployeeId)</h2>
<p class="info">Du är inloggad som administratör</p>

<form method="post" asp-controller="Administrator" asp-action="SaveEmployee">
    <p>
        <label asp-for="EmployeeId" class="label">Id:</label><br />
        @if (ViewBag.NewEmployee)
        {
            <input asp-for="EmployeeId" />
        }
        else
        {
            <input asp-for="EmployeeId" readonly value="@Model.EmployeeId" />
        }
        <span asp-validation-for="EmployeeId" style="color: orange"></span>
    </p>
    <p>
        <label asp-for="EmployeeName" class="label">Namn:</label><br />
        <input asp-for="EmployeeName" />
        <span asp-validation-for="EmployeeName" style="color: orange"></span>
    </p>
    <p>
        <label asp-for="RoleTitle" class="label">Roll:</label><br />
        @if (ViewBag.NewEmployee)
        {
            <select asp-for="RoleTitle" asp-items="@(new SelectList(ViewBag.Roles, "Name", "Name"))">
                <option selected value="">Välj</option>
            </select>
        }
        else
        {
            <select asp-for="RoleTitle" asp-items="@(new SelectList(ViewBag.Roles, "Name", "Name"))" disabled>
                <option selected value="">Välj</option>
            </select>
        }
        <span asp-validation-for="RoleTitle" style="color: orange"></span>
    </p>
    <p>
        <label asp-for="DepartmentId" class="label">Avdelning:</label><br />
        <select asp-for="DepartmentId" asp-items="@(new SelectList(ViewBag.Departments, "DepartmentId", "DepartmentName"))">
            <option selected value="">Välj</option>
        </select>
        <span asp-validation-for="DepartmentId" style="color: orange"></span>
    </p>
    <p>
        <input class="button" type="submit" value="Spara" />
    </p>
</form>

EnvCrime/Views/Administrator/EditStatus.cshtml
@model ErrandStatus

@{
    Layout = "_Staff";
}

<h2>Detaljer för status: @(ViewBag.NewStatus ? "ny status" : Model.StatusId)</h2>
<p class="info">Du är inloggad som administratör</p>

<form method="post" asp-controller="Administrator" asp-action="SaveChanges">
    <p>
        <label asp-for="StatusId" class="label">Id:</label><br />
        @if (ViewBag.NewStatus)
        {
            <input asp-for="StatusId" />
        }
        else
        {
            <input asp-for="StatusId" readonly value="@Model.StatusId" />
        }
        <span asp-validation-for="StatusId" style="color: orange"></span>
    </p>
    <p>
        <label asp-for="StatusName" class="label">Namn:</label><br />
        <input asp-for="StatusName" />
        <span asp-validation-for="StatusName" style="color: orange"></span>
    </p>
    <p>
        <input class="button" type="submit" value="Spara" />
    </p>
</form>