EnvCrime/Components/ErrandListViewComponent.cs
using EnvCrime.Infrastructure.Services;
using EnvCrime.Models.dto;
using Microsoft.AspNetCore.Mvc;

namespace EnvCrime.Components
{
    public class ErrandListViewComponent : ViewComponent
    {
        private readonly ErrandService errandService;
        private readonly EmployeeService employeeService;

        public ErrandListViewComponent(ErrandService errService, EmployeeService empService)
        {
            errandService = errService;
            employeeService = empService;
        }

        public IViewComponentResult Invoke(ErrandSearchQueryDto dto)
        {
            ClearEmptyStrings(dto);

            var errandDtos = errandService.Search(dto);
            ViewBag.RoleTitle = employeeService.GetLoggedInEmployeeRoleTitle();
            
            return View("ErrandList", errandDtos);
        }

        private void ClearEmptyStrings(ErrandSearchQueryDto dto)
        {
            if (dto == null) return;

            dto.EmployeeId = string.IsNullOrWhiteSpace(dto.EmployeeId) ? null : dto.EmployeeId;
            dto.DepartmentId = string.IsNullOrWhiteSpace(dto.DepartmentId) ? null : dto.DepartmentId;
            dto.StatusId = string.IsNullOrWhiteSpace(dto.StatusId) ? null : dto.StatusId;
        }
    }
}

EnvCrime/Components/ErrandViewComponent.cs
using EnvCrime.Infrastructure.Services;
using EnvCrime.Models.poco;
using Microsoft.AspNetCore.Mvc;

namespace EnvCrime.Components
{
    public class ErrandViewComponent : ViewComponent
	{
		private readonly ErrandService errandService;
		private readonly ErrandStatusService errandStatusService;
		private readonly DepartmentService departmentService;
		private readonly EmployeeService employeeService;

		public ErrandViewComponent(ErrandService errService, ErrandStatusService errStatService, DepartmentService deptService, EmployeeService empService)
		{
			errandService = errService;
			errandStatusService = errStatService;
			departmentService = deptService;
			employeeService = empService;
		}

		public IViewComponentResult Invoke(string roleName)
		{ 
			ViewBag.RoleName = roleName;
			
			Errand errand = errandService.GetByIdWithMedia(ViewBag.ErrandId);
			var status = errandStatusService.GetById(errand.StatusId);
			var dept = departmentService.GetById(errand.DepartmentId);
			var employee = employeeService.GetById(errand.EmployeeId);

			ViewBag.StatusName = status.StatusName;
			ViewBag.DepartmentName = dept != null ? dept.DepartmentName : "Ej tillsatt";
			ViewBag.EmployeeName = employee != null ? employee.EmployeeName : "Ej tillsatt";

			return View("SpecificErrand", errand);
		}
	}
}

EnvCrime/Controllers/InvestigatorController.cs
using EnvCrime.Infrastructure.Services;
using EnvCrime.Infrastructure.Shared.Helpers;
using EnvCrime.Models.dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EnvCrime.Controllers
{
    [Authorize(Roles = "Investigator")]
	public class InvestigatorController : Controller
	{

		private readonly AuthenticationHelperService authenticationService;
		private readonly ErrandService errandService;
		private readonly ErrandStatusService errandStatusService;

		public InvestigatorController(AuthenticationHelperService authService, ErrandService errService, ErrandStatusService errStatService)
		{
			authenticationService = authService;
			errandService = errService;
			errandStatusService = errStatService;
		}

		public ViewResult StartInvestigator(ErrandSearchQueryDto searchQuery)
		{
			ViewBag.Statuses = errandStatusService.GetAll();
			LimitSearchToRole(searchQuery);
			return View(searchQuery);
		}

        public ViewResult CrimeInvestigator(int errandId)
		{
			ViewBag.ErrandId = errandId;
			ViewBag.Statuses = errandStatusService.GetAll();
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> UpdateCrime(ErrandUpdateDto dto)
		{
			await errandService.UpdateErrand(dto);
			return RedirectToAction("CrimeInvestigator", new { dto.ErrandId });
		}

        private void LimitSearchToRole(ErrandSearchQueryDto searchQuery)
        {
            searchQuery.EmployeeId = authenticationService.GetLoggedInEmployeeId();
        }
    }
}

EnvCrime/Views/Investigator/CrimeInvestigator.cshtml
@model ErrandUpdateDto

@{
    Layout = "_Staff";
}

@await Component.InvokeAsync("Errand", "handläggare")

<section id="bottomColumn">
    <h3>Redigera ärende</h3>

    <form method="post" asp-controller="Investigator" asp-action="UpdateCrime" enctype="multipart/form-data">
        <!-- onsynliga fältet nedanför används för att föra över "errandId" till motsvarande action-metoden i kontrollern
        då ViewBag inte fungerar där -->
        <input type="hidden" asp-for="ErrandId" value="@ViewBag.ErrandId" />

        <p class="label">Ytterligare information:</p>
        <textarea asp-for="Information" rows="5" cols="60"></textarea>

        <p class="label">Händelser:</p>
        <textarea asp-for="Events" rows="5" cols="60"></textarea>

        <p class="label">Prover:</p>
        <input asp-for="SampleFile" />

        <p class="label">Ladda upp bilder:</p>
        <input asp-for="ImageFile" accept=".jpg, .jpeg, .gif, .bmp, .png" />

        <p class="label">Ändring av status:</p>
        <select asp-for="StatusId" asp-items="@(new SelectList(ViewBag.Statuses, "StatusId", "StatusName"))">
            <option selected disabled>Välj</option>
        </select>
        <p>
            <input class="button" type="submit" value="Spara ändringarna" />
        </p>
    </form>
</section>

EnvCrime/Views/Investigator/StartInvestigator.cshtml
@model ErrandSearchQueryDto

@{
    Layout = "_Staff";
}

<h2>Ärenden</h2>
<p class="info">Du är inloggad som handläggare</p>

<table id="managerForm">
    <tr>
        <td class="label">Välj status:</td>
        <td>&nbsp;</td>
        <td class="label">Ärendenummer:</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <form method="post" asp-controller="Investigator" asp-action="StartInvestigator">
            <td>
                <select asp-for="StatusId" asp-items="@(new SelectList(ViewBag.Statuses, "StatusId", "StatusName"))">
                    <option selected value="">Välj alla</option>
                </select>
            </td>
            <td><input class="button" type="submit" value="Hämta lista" /></td>
        </form>
        <form method="post" asp-controller="Investigator" asp-action="StartInvestigator">
            <td><input asp-for="RefNumber" /></td>
            <td><input class="button" type="submit" value="Sök" /></td>
        </form>
    </tr>
</table>

@await Component.InvokeAsync("ErrandList", Model)